### ISSUE TITLE
Loving the game, but the background is a bit boring!

### ISSUE THREAD

**Issue by finneyj** [finneyj/JoesGame#1]

**Comment by ezzini** [comment]
What do you have in mind?

**Comment by finneyj** [comment]
Well... funny you should say that :)

How about a starfield?

**Comment by ezzini** [comment]
Sounds good, go for it

**Comment by finneyj** [comment]
Done! See commit c52b1f4127f0ab8ce9d7c92e5741a36fb0585f24
